### ISSUE TITLE
Set up

### ISSUE THREAD

**Issue by mozzarelli3** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-team-33#1]
```[tasklist]
### Tasks
- [x] Clone repo
- [x] run npm install
- [x] set up render db
- [x] add db string and port to .env file
- [x] reset database
- [x] npm run dev - check if working
- [x] rename function and route handler names to artists and albums
```
