### ISSUE TITLE
GET

### ISSUE THREAD

**Issue by mozzarelli3** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-team-33#2]
```[tasklist]
### Tasks
- [x] Write pseudocode for each function
- [x] GET request route handler - artists
- [ ] GET request route handler - albums
- [x] GET function -  artists
- [ ] GET function - albums
```
