### ISSUE TITLE
GET by ID

### ISSUE THREAD

**Issue by mozzarelli3** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-team-33#3]
```[tasklist]
### Tasks
- [x] Write pseudocode for each function
- [x] GET by ID function - artist
- [x] GET by ID function - album
- [x] GET by ID route handler - artist
```
