### ISSUE TITLE
POST

### ISSUE THREAD

**Issue by mozzarelli3** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-team-33#4]
```[tasklist]
### Tasks
- [ ] Write pseudocode for each function
- [ ] POST request route handler - artist
- [ ] POST request route handler - album
- [ ] POST function - artists
- [ ] POST function - albums
```
