### ISSUE TITLE
PATCH

### ISSUE THREAD

**Issue by mozzarelli3** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-team-33#5]
```[tasklist]
### Tasks
- [ ] Write pseudocode for each function
- [ ] PATCH request route handler - artist
- [ ] PATCH request route handler -album
- [ ] PATCH function - artists
- [ ] PATCH function - albums
```
