### ISSUE TITLE
DELETE

### ISSUE THREAD

**Issue by mozzarelli3** [SchoolOfCode/bc17-w5-d4-hackathon-rest-api-postgres-team-33#6]
```[tasklist]
### Tasks
- [ ] Write pseudocode for each function
- [ ] DELETE request handler - artists
- [ ] DELETE request handler - albums
- [ ] DELETE function - artists
- [ ] DELETE function - albums
```
